# .github/release.yml

changelog:
  exclude:
    labels:
      - Ignore for Release
    #authors:
    #  - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - module-release:major
        - Semver Major
        - breaking-change
    - title: New Features and Enhancements 🎉
      labels:
        - module-release:minor
        - Semver Minor
        - Enhancement
        - feature
    - title: Bug Fixes and Hotfixes 🐛
      labels:
        - Semver Patch
        - bug
        - hotfix
    - title: Security 🔒
      labels:
        - security
    - title: Documentation and Guides 📚
      labels:
        - Documentation Required
        - documentation
    - title: Dependencies 📦
      labels:
        - dependencies
        - renovate
    - title: Infrastructure and Tooling 🛠️
      labels:
        - GitHub Actions
        - ci
        - maintenance
        - Chore
    - title: Other Changes
      labels:
        - "*"
