formatter: "markdown table" # this is required
header-from: ../../terraform-docs/tf_header.txt
footer-from: ../../terraform-docs/tf_footer.txt
sections:
  #hide: []
  show: []
  #hide-all: false # deprecated in v0.13.0, removed in v0.15.0
  #show-all: true  # deprecated in v0.13.0, removed in v0.15.0
content: |-
  {{ .Header }}

  ---

  <!-- Readme Navigation -->

  [(Back to the Table of Contents)](#table-of-contents)

  ---

  {{ .Requirements }}

  ---

  <!-- Readme Navigation -->

  [(Back to the Table of Contents)](#table-of-contents)

  ---

  ```hcl
  {{ include "example.tf" }}
  ```


  ---

  <!-- Readme Navigation -->

  [(Back to the Table of Contents)](#table-of-contents)

  ---

  {{ .Resources }}

  ---

  <!-- Readme Navigation -->

  [(Back to the Table of Contents)](#table-of-contents)

  ---

  {{ .Inputs }}

  ---

  <!-- Readme Navigation -->

  [(Back to the Table of Contents)](#table-of-contents)

  ---

  {{ .Outputs }}

  ---

  <!-- Readme Navigation -->

  [(Back to the Table of Contents)](#table-of-contents)

  ---

  {{ .Modules }}

  ---

  <!-- Readme Navigation -->

  [(Back to the Table of Contents)](#table-of-contents)

  ---

  {{ .Footer }}

  ---

  <!-- Readme Navigation -->

  [(Back to the Table of Contents)](#table-of-contents)

  ---
output:
  file: README.md
  mode: inject
  template: |-
    <!-- start_of_terraform_docs -->
    {{ .Content }}
    <!-- end_of_terraform_docs -->
output-values:
  enabled: false
  #from: terraform-docs/default_values.json #environment\default.tfvars
sort:
  enabled: true
  by: required
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

Precommit-Verified: 60390380d1566e2e0a26b7823cd3f5cf6ad48791940bb33236ffc555ef8e6d56
