APPLY_FIXES: all # all, none, or list of linter keys
AZURE_COMMENT_REPORTER: true
CLEAR_REPORT_FOLDER: true
CONFIG_REPORTER: true
CONFIG_REPORTER_SUB_FOLDER: IDE-config
FILEIO_REPORTER: false #if set to true this will generate a hyperlink to a report on file.io DO NOT ENABLE
JSON_REPORTER: true
JSON_REPORTER_OUTPUT_DETAIL: "detailed"
MARKDOWN_DEFAULT_STYLE: markdownlint
PRINT_ALPACA: true
PRINT_ALL_FILES: true
SARIF_REPORTER: true # new feature
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: true
TAP_REPORTER: true #if set to true reports all results as tap files, do this to convert to JUnit to keep a standardised test result format
TAP_REPORTER_SUB_FOLDER: tap #if enabled allows you to define a different folder location for the tap result files. tap is the default directory
TERRAFORM_CHECKOV_ARGUMENTS:
  #- "--directory /Repo"
  - "--include-all-checkov-policies" # settings to allow integration with bridgecrew using pipeline variables
TERRAFORM_CHECKOV_CLI_LINT_MODE: file # Options are file (default), list_of_files or project. Project scans from the root of the Repo
TERRAFORM_KICS_ARGUMENTS:
  - "-m"
  - "--config ../kics.config"
  - "--output-path KICSReports"
  - "--output-name kics-report-$(environment_tag)" # settings to match KICS pipeline
TERRAFORM_KICS_CLI_LINT_MODE: file # Options are file (default), list_of_files or project. Project scans from the root of the Repo
TERRAFORM_TERRASCAN_ARGUMENTS:
  - "--verbose"
  - "--show-passed"
  #- "--log-output-dir /reports"
  #- "--output human"
  #- "--output junit-xml"
  #- "--output sarif" # settings to match terrascan pipeline
TERRAFORM_TFLINT_ARGUMENTS:
  - "--color"
  #- "--format sarif"
  #- "--format junit"
TEXT_REPORTER: true #this is enabled by default anyway, but i find it is nicer to specifically declare it
TEXT_REPORTER_SUB_FOLDER: text #if enabled allows you to define a different folder location for the text result files.

Precommit-Verified: 840b0bb38e7d8052862c572f7b9052352b54a92ea06370f438abe56a19ed1e6b
