formatter: "markdown table" # this is required
version: "0.17"
header-from: /terraform-docs/tf_header.txt
footer-from: /terraform-docs/tf_footer.txt
recursive:
  enabled: false
  #path: .terraform\modules
sections:
  #hide: []
  show: []
  #hide-all: false # deprecated in v0.13.0, removed in v0.15.0
  #show-all: true  # deprecated in v0.13.0, removed in v0.15.0
content: |-
  {{ .Header }}

  ---

  <!-- Readme Navigation -->

  [(Back to the Top)](#Terraform)

  ---

  {{ .Requirements }}

  ---

  <!-- Readme Navigation -->

  [(Back to the Top)](#Terraform)

  ---

  <!-- consuming Module_Name -->
  ## Consuming Module_Name

    To consume this module add the following to your module.tf:
  ```hcl
    module "Module_Name" {
      {{"\t"}} source  = "github.com/DownAtTheBottomOfTheMoleHole/Module_Name.git"
  {{- if .Module.RequiredInputs }}
      {{"\n\t"}} # Required variables
      {{- range .Module.RequiredInputs }}
      {{"\t"}} {{ .Name }}  = {{ .GetValue }}
      {{- end }}
      {{- end }}
  {{- if .Module.OptionalInputs }}
      {{"\n\t"}} # Optional variables
      {{- range .Module.OptionalInputs }}
      {{"\t"}} {{ .Name }}  = {{ .GetValue | printf "%s" }}
      {{- end }}
      {{- end }}
    }
    ```

  ## Example 1

  ```hcl
  {{ include "examples/example-1/modules.tf" }}


  ---

  <!-- Readme Navigation -->

  [(Back to the Top)](#Terraform)

  ---

  {{ .Resources }}

  ---

  <!-- Readme Navigation -->

  [(Back to the Top)](#Terraform)

  ---

  {{ .Inputs }}

  ---

  <!-- Readme Navigation -->

  [(Back to the Top)](#Terraform)

  ---

  {{ .Outputs }}

  ---

  <!-- Readme Navigation -->

  [(Back to the Top)](#Terraform)

  ---

  {{ .Modules }}

  ---

  <!-- Readme Navigation -->

  [(Back to the Top)](#Terraform)

  ---

  {{ .Footer }}

  ---

  <!-- Readme Navigation -->

  [(Back to the Top)](#Terraform)

  ---
output:
  file: TERRAFORM.md
  mode: inject
  template: |-
    <!-- start_of_terraform_docs -->
    {{ .Content }}
    <!-- end_of_terraform_docs -->
output-values:
  enabled: true
  from: terraform-docs/default_values.json #environment\default.tfvars
sort:
  enabled: true
  by: required
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
