---
extends: default
rules:
  new-lines:
    level: warning
    type: unix
  line-length:
    max: 500
  comments:
    min-spaces-from-content: 1 # Used to follow prettier standard: https://github.com/prettier/prettier/pull/10926

Precommit-Verified: f2fce78cda41a42b3d3e9d4e7b65b40a321e47e17111fd580e639ec90f444a1d
