name: 🚀 Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: DownAtTheBottomOfTheMoleHole/.github/.github/workflows/auto-release.yml@e6fbeea8427490b370061b8f20113224cd38f5c2 # main
    secrets: inherit
    permissions:
      contents: write
